README.md
docs/developer-guide.md
docs/user-guide.md

Added a main readme in the project folder with a dev and user readme in docs folder.

Added Readme.

---

benchmarks/dummy_benchmark/implementation.py
common/benchmark_factory.py
user_interfaces/cli.py
user_interfaces/utils.py

The bugs seen were as follows:
1. Line indentation error in dummy benchmark implementation.
2. Benchmark factory had open file which was caught while unit testing.
3. Logging was causing permission error and hence been commented for now.
4. Singular custom exception class that was used is now removed.

Fixed some minor bugs which came up while testing the code.

---

user_interfaces/cli.py

CLI wont prompt user if they wish to install setup, it will be done automatically.

Removed CLI prompt for setup.

---

docs/user-guide.md

This PR makes changes to user-guide to change getSettings example and other minor changes.

Modified Readme to accomodate getSettings defination change

---

tests/test_user_interfaces_utils.py

Added tests for util functions in user_interfaces.

Added tests for utils used in user interfaces.

---

benchmarks/blender_benchmark/README.md

The README includes the following:
1. Project website
2. Available scenes
3. Devices supported
4. Blender benchmark CLI Docs downloaded with the executable 
Please suggest any changes/modifications that you'd like to make

Added README for blender benchmark

---

docs/developer-guide.md

Fixed link to the class diagram

---

benchmarks/blender_benchmark/implementation.py
common/benchmark_suite.py
user_interfaces/cli.py

There was a bug(#72 ) that wasn't setting up the requirements when run as a suite.
It has been fixed in this PR.

Fixed issue causing blender_suite to not run.

---

docs/developer-guide.md
docs/user-guide.md

Documentation for log functionality in UI.

---

user_interfaces/cli.py

[Solves #79 partially(docs remain which will be covered in another PR)] . 
Modifications tested on Linux and Windows.

Fixes the issue of list-logs not showing any enteries.

---

suites/blender_suite_1.json

Fixed the typos in blender_suite. This solves #83

Modified suite defination in blender_suite

---

benchmarks/blender_benchmark/implementation.py
benchmarks/dummy_benchmark/implementation.py
common/benchmark_suite.py
user_interfaces/interface_skeleton.py

Fixes issue #84 (and also similar issues #86 and #88 )

Fixed issue given by blender-benchmark

---

user_interfaces/cli.py

Case where user could make a suite without specifying a benchmark

Fixed an exception case in Suite maker

---

user_interfaces/cli.py

Please recommend any modifications to the below changes.

Added some comments to cli interface

---

user_interfaces/cli.py

This PR tries to refactor the CLI interface code for the following purposes:
1. Makes it easier for readers
2. Doesn't trigger flake8 
[Ps. There is no fundamental code change except the use of dictionary get instead of if else in the below lines]
https://github.com/Open-ForBC/OpenForBC-Benchmark/blob/edc72df31cffe33a128718f933a5e4eb4bb4ce7a/user_interfaces/cli.py#L71-L76

Refactoring of CLI benchmark code.

---

benchmarks/blender_benchmark/implementation.py
user_interfaces/cli.py

This PR serves as a fix for victor benchmark and adds better more vigorous error catching to cli, hence solving #100 
After this PR the code wont break if victor is chosen as a scene in blender benchmark. 
Even if several benchmarks follow/ precede victor, it works the same.

Fix for victor benchmark

---

tests/test_user_interfaces_utils.py

Tests added for util functions in user interface. The following functionalities are tested:
1. Table making function
2. Logging function

Added some more tests

---

docs/user-guide.md

This PR does minor modifications to the user-guide, it brings the help command above and adds details on the --csv flag.

Modified the user-guide

---

.github/workflows/CI.yml
benchmarks/matmulCpp_benchmark/README.md
benchmarks/matmulCpp_benchmark/benchmark_info.json
benchmarks/matmulCpp_benchmark/implementation.py
benchmarks/matmulCpp_benchmark/matmulCpp.cpp
benchmarks/matmulCpp_benchmark/settings/Matrix_557x489.json
benchmarks/matmulCpp_benchmark/settings/Matrix_57x89.json
benchmarks/matmulCpp_benchmark/settings/Matrix_700x800.json
benchmarks/matmulCpp_benchmark/setup.sh
bin/test_matmulCpp.sh

Add Matrix Multiplication Benchmark written in C++.

Add Matrix Multiplication Benchmark written in C++

---

benchmarks/matmulCpp_benchmark/matmulCpp.cpp

- Fix clang-tidy warnings
- Format code according to defined `.clang-format`

Clean up cpp matmul benchmark

---

README.md
benchmarks/CIFAR_realtime_benchmark/README.md
benchmarks/MNIST_FCNeuralNetwork/README.md
benchmarks/MNIST_realtime_benchmark/MNIST_realtime.py
benchmarks/MNIST_realtime_benchmark/README.md
benchmarks/TeacherStudent_realtime_benchmark/README.md
benchmarks/TeacherStudent_realtime_benchmark/TeacherStudent_realtime.py
benchmarks/dummy_py_benchmark/README.md

Update benchmarks and repository README.md and change MNIST real time benchmark training parameters.

Update  READMEs and change MNIST real time benchmark parameters

---

benchmarks/CIFAR_realtime_benchmark/CIFAR_realtime.py
benchmarks/CIFAR_realtime_benchmark/benchmark.json
benchmarks/CIFAR_realtime_benchmark/presets/test.json
benchmarks/CIFAR_realtime_benchmark/requirements.txt
benchmarks/MNIST_realtime_benchmark/MNIST_realtime.py
benchmarks/MNIST_realtime_benchmark/benchmark.json
benchmarks/MNIST_realtime_benchmark/presets/test.json
benchmarks/MNIST_realtime_benchmark/requirements.txt
benchmarks/TeacherStudent_realtime_benchmark/TeacherStudent_realtime.py
benchmarks/TeacherStudent_realtime_benchmark/benchmark.json
benchmarks/TeacherStudent_realtime_benchmark/presets/test.json
benchmarks/TeacherStudent_realtime_benchmark/requirements.txt

Fixes requirements files.
Defines test preset (able to run on CPU).
Defines the `test_preset` to call the right preset.

Fixing various issues with TS, MNIST and CIFAR

---

benchmarks/CIFAR_realtime_benchmark/CIFAR_realtime.py
benchmarks/CIFAR_realtime_benchmark/presets/inference-unlimited.json
benchmarks/CIFAR_realtime_benchmark/presets/inference.json
benchmarks/CIFAR_realtime_benchmark/presets/training-long.json
benchmarks/CIFAR_realtime_benchmark/presets/training.json
benchmarks/MNIST_realtime_benchmark/MNIST_realtime.py
benchmarks/MNIST_realtime_benchmark/presets/inference-unlimited.json
benchmarks/MNIST_realtime_benchmark/presets/inference.json
benchmarks/MNIST_realtime_benchmark/presets/training-long.json
benchmarks/MNIST_realtime_benchmark/presets/training.json
benchmarks/TeacherStudent_realtime_benchmark/TeacherStudent_realtime.py
benchmarks/TeacherStudent_realtime_benchmark/presets/inference-unlimited.json
benchmarks/TeacherStudent_realtime_benchmark/presets/inference.json
benchmarks/TeacherStudent_realtime_benchmark/presets/training-long.json
benchmarks/TeacherStudent_realtime_benchmark/presets/training.json

Introducing long-running and unlimited presets and handling Ctrl-C gracefully

---

README.md
docs/user-guide.md

Move user install guide into user-guide.md

---

.github/workflows/test_benchmarks.yml

Benchmark tests are now run wheneved a PR modifies a benchmark or the
tool code.
Closes #181

Run all benchmarks' tests on every PR

---

openforbc_benchmark/benchmark.py
openforbc_benchmark/cli/benchmark.py
openforbc_benchmark/cli/state.py
openforbc_benchmark/cli/suite.py
openforbc_benchmark/json.py
openforbc_benchmark/utils.py

- Make benchmarks fail when stats are not matched
- Add code documentation to utils module
- Add code documentation to json module
- Add code documentation to benchmark module
- Add cli modules code documentation

Add code documentation

---

benchmarks/TCGA_topicmodeling/TCGA_topicmodeling_benchmark.py
benchmarks/TCGA_topicmodeling/benchmark.json
benchmarks/TCGA_topicmodeling/presets/test.json
benchmarks/TCGA_topicmodeling/requirements.txt

- Clean up TCGA_topicmodeling benchmark code
- Update TCGA_topicmodeling stats definition

Fix TCGA_topicmodeling benchmark stats

---

benchmarks/MNIST_FCNeuralNetwork/MNIST_FCNeuralNetwork_benchmark.py
benchmarks/blender_benchmark/setup.py
benchmarks/matmulCpp_benchmark/matmulCpp.cpp
benchmarks/matmulCpp_benchmark/matmulCpp_benchmark.cpp
benchmarks/matmul_benchmark/matmul_benchmark.py
benchmarks/tensorflow_benchmark/base.py
benchmarks/tensorflow_benchmark/cifar.py
benchmarks/tensorflow_benchmark/mnist.py
benchmarks/tensorflow_benchmark/tcga.py
benchmarks/tensorflow_benchmark/teacherstudent.py
openforbc_benchmark/benchmark.py
openforbc_benchmark/cli/app.py
openforbc_benchmark/cli/benchmark.py
openforbc_benchmark/cli/interactive.py
openforbc_benchmark/cli/state.py
openforbc_benchmark/cli/suite.py
openforbc_benchmark/json.py
openforbc_benchmark/utils.py
pyproject.toml

This PR adds license headers to source files and also sets license for the
python package.

Add license information to the project

---

openforbc_benchmark/benchmark.py

Allow stats regexes to match multiple lines

Fix multiline regexes

---

.github/workflows/test_benchmarks.yml

This PR adds the possibility to manually trigger the CI workflows

add manual trigger for workflows
