Open-ForBC/OpenForBC-Benchmark

user_interfaces/cli.py
This PR solves #36 and allows user to run interactive mode with ```python3 user_interfaces/cli.py interactive```
=> Removed interactive prompt in CLI interface.

benchmarks/blender_benchmark/implementation.py, benchmarks/blender_benchmark/setup.py
This PR corrects the path set for downloading the benchmark executables in ``` /bin ```.
This solves #22 also is the reason for error seen in #40 .
=> Added fixes for blender benchmark executable download.

docs/developer-guide.md
to add info about why we take implementation file in ```bechmark_info.json```.
=> Modified developer guide

benchmarks/blender_benchmark/benchmark_info.json, benchmarks/dummy_benchmark/benchmark_info.json, user_interfaces/cli.py
Space to default has been replaced with a default_settings parameter in benchmark_info.json .
The user is not prompted with choosing settings now, if default is present.
=> Default setting for benchmarks

benchmarks/blender_benchmark/README.md, benchmarks/blender_benchmark/README.txt
This is a PR to solve #75 
Currently the readme is in the blender benchmark folder (ie. benchmarks>blender_benchmark>README.txt)
Alternatively it can be put in another folder (maybe /archive or /more-docs ) ?
=> Added blender-provided readme for reference

user_interfaces/cli.py
This PR aims to solve issue #82 
[ PS. The check on line # 407 check might fail in a case where the benchmark name has "suite" in it and the settings contains date in the format we use. ]
=> Adding settings column to list-logs

.clang-format, .clang-tidy
The `.clang-format` is based on Google style guide with some additions
such as specifying the c++ standard (c++11).
The `.clang-tidy` disables all the default checks and enables a sensible
set of them, it also specifies to use the defined `.clang-format` to
format fixes applied automatically.
=> Define clang-tidy and clang-format configurations

docs/developer-guide.md, jsonschema/benchmark.schema.json, jsonschema/benchmark_preset.schema.json, jsonschema/benchmark_stats.schema.json
This new benchmark definition policy will replace the current `implementation.py`-based benchmark layout and allow for better flexibility in benchmarks' implementations: the currently used python method call interface will be replaced by a simpler process execution.
The two main challenges in this step are:
- configuring benchmarks to use the chosen preset
- parsing a benchmark's output to extract data
We address the first one by allowing benchmark developers to define arguments that a preset will pass to the benchmark executable, or setup commands to be launched before running the benchmark.
The benchmark's output can be specified via a simple script/command that will output data in a well-defined format or by using *regex*es that will match data in specific files.
Closes #136
=> Define new benchmark interface

openforbc_benchmark/jsonschema/benchmark_suite.schema.json
The `benchmark_run` type was defined incorrectly (`properties` field was
missing) and required fields were not specified. `additionalProperties` is now
set to `false` so that adding unrecognized properties to a suite definition
will invalidate it.
=> Fix benchmark suite json schema

.github/workflows/test_benchmarks.yml, benchmarks/dummy_benchmark/benchmark.json, benchmarks/dummy_py_benchmark/benchmark.json, docs/developer-guide.md, openforbc_benchmark/benchmark.py, openforbc_benchmark/cli/benchmark.py, openforbc_benchmark/json.py, openforbc_benchmark/jsonschema/benchmark.schema.json, tests/cli/test_benchmark.py, tests/test_benchmark.py, tests/test_json.py
This will allow benchmarks to define their own tests, which can be run in the
CI pipeline.
Tests will be considered passing if all the specified commands return a zero
exit code.
=> Add `test_command` field to benchmark's definition

openforbc_benchmark/benchmark.py, openforbc_benchmark/utils.py, tests/test_benchmark.py
The `__repr__` method of `Runnable` broke virtualenvs by modifying the
environment. The old behaviour is now replaced.
Closes #169
=> Fix virtualenv environment

.github/workflows/test.yml
Benchmarks now have their own test pipeline, specified in the
`test_command` field.
=> Disable flake8 in benchmarks

openforbc_benchmark/benchmark.py, openforbc_benchmark/cli/benchmark.py
Benchmarks will now fail if any stat's regex will not match a line in
the benchmark output.
=> Make benchmarks fail when stats match fails

openforbc_benchmark/cli/benchmark.py
Previously an error was issued and the CLI would terminate with retcode
!= 0.
=> Warn only when stats decode fails

.github/workflows/test.yml, poetry.lock, pyproject.toml, requirements.txt, tox.ini
This PR updates all the dependencies and also declares correct python versions
in `tox.ini`.
`tox` may now be used to run tests in all supported python versions!
Fixes #190
=> Upgrade release and development dependencies

.github/workflows/clang_tidy.yml, .github/workflows/test.yml
- Moved clang-tidy job to a separate workflow, which runs only when
`.c/.cpp/.h/.hpp` files are modified
Fixes #191
=> Run clang-tidy only when c/c++ source modified

.github/workflows/test_benchmarks.yml
Try to run benchmark only if `benchmark.json` exists.
Fixes #207
=> Fix benchmarks's CI workflow

openforbc_benchmark/cli/benchmark.py
This prevents the spinner text from overflowing into the history.
Old behaviour:
With this PR applied:
=> Ellipsize spinner text when too long

.flake8
E203 is incorrectly issued by flake8 in slices.
=> Ignore flake E203

benchmarks/CIFAR_realtime_benchmark/CIFAR_realtime.py, benchmarks/CIFAR_realtime_benchmark/benchmark.json, benchmarks/CIFAR_realtime_benchmark/presets/test.json, benchmarks/CIFAR_realtime_benchmark/requirements.txt, benchmarks/MNIST_realtime_benchmark/MNIST_realtime.py, benchmarks/MNIST_realtime_benchmark/benchmark.json, benchmarks/MNIST_realtime_benchmark/presets/test.json, benchmarks/MNIST_realtime_benchmark/requirements.txt, benchmarks/TeacherStudent_realtime_benchmark/TeacherStudent_realtime.py, benchmarks/TeacherStudent_realtime_benchmark/benchmark.json, benchmarks/TeacherStudent_realtime_benchmark/presets/test.json, benchmarks/TeacherStudent_realtime_benchmark/requirements.txt
This PR removes unused stats in realtime benchmarks and ensures that they
output all of them in every preset, so that no warning is issued by
`o4bc-bench`.
Closes #192
=> Fix realtime benchmarks stats

benchmarks/blender_benchmark/README.md
- add requirement for libxi6
- specify metal runs only on mac
Issue #223
=> update blender README

benchmarks/MNIST_FCNeuralNetwork/requirements.txt, benchmarks/tensorflow_benchmark/requirements.txt
Replace `sklearn` with `scikit-learn` in benchmarks' requirements
=> Fix sklearn requirement

.github/workflows/test_benchmarks.yml
Will later try to find out a way to make gpu benchmarks run in CI, but as of now it's not possible...
=> Disable phoronix benchmarks in tests

benchmarks/MNIST_FCNeuralNetwork/requirements.txt, benchmarks/matmul_benchmark/requirements.txt
`tensorflow-gpu` has been removed and replaced by plain `tensor flow` package.
=> Fix tensorflow dependency after TF-gpu removal
